receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://localhost:3000"
          allowed_headers: ["*"]
      grpc:
        endpoint: 0.0.0.0:4317
  redis:
    endpoint: redis:6379
    collection_interval: 60s
    password: "your_secure_redis_password_here"
    tls:
      insecure: true
    metrics:
      redis.maxmemory:
        enabled: true
      redis.cmd.latency:
        enabled: true

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024

  memory_limiter:
    check_interval: 1s
    limit_mib: 512

  resource:
    attributes:
      - key: service.name
        value: ethereal-nexus-dashboard
        action: upsert

exporters:

  #signoz
  otlp:
    endpoint: "${SIGNOZ_ENDPOINT}"
    headers:
      signoz-ingestion-key: "${SIGNOZ_API_KEY}"
    tls:
      insecure: false

  otlphttp:
    endpoint: "${NEWRELIC_ENDPOINT}"
    headers:
      api-key: "${NEWRELIC_API_KEY}"

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [ health_check, pprof, zpages ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ otlp, otlphttp]
    metrics:
      receivers: [ redis, otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ otlp, otlphttp ]
    logs:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ otlp, otlphttp ]
